[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173

# Direct database access endpoints
[[redirects]]
  from = "/db/auth"
  to = "/.netlify/functions/neon-auth"
  status = 200

[[redirects]]
  from = "/db/users"
  to = "/.netlify/functions/neon-users"
  status = 200

[[redirects]]
  from = "/db/inventory"
  to = "/.netlify/functions/neon-inventory"
  status = 200

[[redirects]]
  from = "/db/categories"
  to = "/.netlify/functions/neon-categories"
  status = 200

[[redirects]]
  from = "/db/requests"
  to = "/.netlify/functions/neon-requests"
  status = 200

# Legacy API endpoints
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Legacy Neon endpoints
[[redirects]]
  from = "/neon/categories"
  to = "/.netlify/functions/neon-categories"
  status = 200

[[redirects]]
  from = "/neon/test"
  to = "/.netlify/functions/test-neon"
  status = 200

[[redirects]]
  from = "/db/test"
  to = "/.netlify/functions/test-db"
  status = 200

[[redirects]]
  from = "/db/test-inventory"
  to = "/.netlify/functions/test-inventory"
  status = 200

[[redirects]]
  from = "/db/test-connection"
  to = "/.netlify/functions/test-db-connection"
  status = 200

[[redirects]]
  from = "/neon/auth"
  to = "/.netlify/functions/neon-auth"
  status = 200

[[redirects]]
  from = "/neon/auth/login"
  to = "/.netlify/functions/neon-auth"
  status = 200

[[redirects]]
  from = "/neon/auth/register"
  to = "/.netlify/functions/neon-auth"
  status = 200

[[redirects]]
  from = "/neon/query"
  to = "/.netlify/functions/neon-query"
  status = 200

[[redirects]]
  from = "/neon/init-db"
  to = "/.netlify/functions/init-neon-db"
  status = 200

[[redirects]]
  from = "/neon/inventory"
  to = "/.netlify/functions/neon-inventory"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
